export const ImageConst = {
  plus_png: require('/Users/mac/Documents/Chatedemo/asset/Image/plus.png'),
  email_png: require('/Users/mac/Documents/Chatedemo/asset/Image/email.png'),
  user_png: require('/Users/mac/Documents/Chatedemo/asset/Image/user.png'),
  padlock_png: require('/Users/mac/Documents/Chatedemo/asset/Image/padlock.png'),
  google_png: require('/Users/mac/Documents/Chatedemo/asset/Image/google.png'),
  facebook_png: require('/Users/mac/Documents/Chatedemo/asset/Image/facebook.png'),
  arrow_png: require('/Users/mac/Documents/Chatedemo/asset/Image/arrow.png'),
  user_png: require('/Users/mac/Documents/Chatedemo/asset/Image/user.png'),
  add_friend_png: require('/Users/mac/Documents/Chatedemo/asset/Image/add-friend.png'),
  cancel_png: require('/Users/mac/Documents/Chatedemo/asset/Image/cancel.png'),
  search_interface_symbol_png: require('/Users/mac/Documents/Chatedemo/asset/Image/search-interface-symbol.png'),
  group_png: require('/Users/mac/Documents/Chatedemo/asset/Image/group.png'),
  add_user_png: require('/Users/mac/Documents/Chatedemo/asset/Image/add-user.png'),
  multiple_users_silhouette_png: require('/Users/mac/Documents/Chatedemo/asset/Image/multiple-users-silhouette.png'),
  images_removebg_preview_png: require('/Users/mac/Documents/Chatedemo/asset/Image/images-removebg-preview.png'),
  call_png: require('/Users/mac/Documents/Chatedemo/asset/Image/call.png'),
  bell_png: require('/Users/mac/Documents/Chatedemo/asset/Image/bell.png'),
  options_png: require('/Users/mac/Documents/Chatedemo/asset/Image/options.png'),
  camera: require('/Users/mac/Documents/Chatedemo/asset/Image/photo-camera-interface-symbol-for-button.png'),
  gallery_png: require('/Users/mac/Documents/Chatedemo/asset/Image/gallery.png'),
  send_message_png: require('/Users/mac/Documents/Chatedemo/asset/Image/send-message.png'),
  zoom_png: require('/Users/mac/Documents/Chatedemo/asset/Image/zoom.png'),
};
